### ISSUE TITLE
Memo of conception

### ISSUE THREAD

**Issue by isaoeka** [isaoeka/VideoPlayerSample-iOS#1]
# TODO

## UI design
- [x] Refer to Youtube's UI
- [x] Consider to some extent Human Interface Guidelines
- [x] Use Font Awesome for images
- [x] Make wireframe write on paper
    - <img src="https://user-images.githubusercontent.com/2672857/46905937-c7f8fc80-cf35-11e8-9b86-f481be20dedc.png" width="400">

### Step 1
- [x] Use `.xcconfig` for config value
- [x] Make a simple video player
    - Make it with `MVP` or` Redux`

### Step 2
- [x] Finish up the video player
- [x] Full screen play in landscape

### Step 3
- [x] Finishing touches
- [x] Review by yourself

**Comment by isaoeka** [comment]
🚶
